### ISSUE TITLE
Create structure the paper in LateX. 

### ISSUE THREAD

**Issue by EvertonMelo** [republicprotocol/whitepaper#2]
suggestion to create a structure in ["latex"](http://www.latexeditor.org/)

it is easier to translate and change content than in .pdf.

**Comment by EvertonMelo** [comment]
@loongy you did not do anything.
so the improvement can not be closed.

**Comment by loongy** [comment]
I didn't close this issue, if you look at the history above, you closed it 10 days ago.

**Comment by EvertonMelo** [comment]
@loongy 

ok.
